# Generated by Django 4.1.1 on 2022-10-03 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Married_opt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('married_select', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home_Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20, null=True)),
                ('Last_Name', models.CharField(max_length=20, null=True)),
                ('Phone_Number', models.CharField(max_length=20, null=True)),
                ('Email', models.CharField(max_length=20, null=True)),
                ('Permanent_Address', models.CharField(max_length=20, null=True)),
                ('Mailing_Address', models.CharField(max_length=20, null=True)),
                ('Postal_code', models.CharField(max_length=20, null=True)),
                ('City', models.CharField(max_length=20, null=True)),
                ('Education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.education_level')),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.gender')),
                ('Job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.job_type')),
                ('Married', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.married_opt')),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.property')),
                ('Province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.province')),
            ],
        ),
    ]
